module.exports = function (config) {
    config.set({
        basePath: '../..',
        frameworks: ['jasmine'],
        browsers: ['Firefox'],
        browserNoActivityTimeout: 100000,
        autoWatch: false,
        singleRun: true,
        files: [
            {pattern: 'test/data/*.json', watched: true, served: true, included: false},
            {pattern: 'app/images/*', included: false, served: true},
            'app/components/q/q.js',
            'app/components/angular/angular.js',
            // mock out all the micro-frontends
            'test/__mocks__/micro-frontends.js',
            'app/components/ngDialog/js/ngDialog.js',
            'app/components/angular-route/angular-route.js',
            'app/components/angular-sanitize/angular-sanitize.js',
            'app/components/jquery/jquery.js',
            'app/components/jquery.cookie/jquery.cookie.js',
            'app/components/jasmine-jquery/lib/jasmine-jquery.js',
            'app/components/jquery-ui/ui/jquery.ui.widget.js',
            'app/components/jquery-ui/ui/jquery.ui.tooltip.js',
            'app/components/angular-mocks/angular-mocks.js',
            'app/components/ngInfiniteScroll/build/ng-infinite-scroll.js',
            'app/components/d3/d3.min.js',
            'app/components/nvd3/nv.d3.min.js',
            'app/components/angularjs-nvd3-directives/dist/*.js',
            'app/components/moment/min/moment.min.js',
            'app/components/angular-ui-calendar/src/calendar.js',
            'app/components/fullcalendar/dist/fullcalendar.min.js',
            'app/components/fullcalendar-scheduler/dist/scheduler.min.js',
            'app/components/angular-elastic/elastic.js',
            'app/components/angular-ivh-treeview/dist/ivh-treeview.min.js',
            'app/components/offline/offline.min.js',
            'app/components/angular-ui-router/release/angular-ui-router.js',
            'app/components/lodash/dist/lodash.min.js',
            'app/components/angular-ui-select2/src/select2.js',
            'app/components/angular-bindonce/bindonce.js',
            'app/components/ng-tags-input/ng-tags-input.min.js',
            'app/components/stacktrace-js/stacktrace.js',
            'app/components/ng-clip/src/ngClip.js',
            'app/components/zeroclipboard/dist/ZeroClipboard.js',
            'app/components/angular-translate/angular-translate.js',
            'app/components/angular-file-upload/dist/angular-file-upload.min.js',
            'app/components/angular-cookies/angular-cookies.js',
            'app/components/angular-translate-storage-local/angular-translate-storage-local.js',
            'app/components/angular-translate-storage-cookie/angular-translate-storage-cookie.js',
            'app/components/angular-translate-loader-static-files/angular-translate-loader-static-files.js',
            'app/components/hustle/hustle.js',
            'app/lib/modernizr.custom.80690.js',
            'app/lib/angular-workers/dist/angular-workers.js',
            'app/common/constants.js',
            'app/common/util/init.js',
            'app/common/util/**.js',
            'app/common/domain/init.js',
            'app/common/domain/**/*.js',
            'app/**/init.js',
            'app/**/constants.js',
            'app/common/uicontrols/**/*.js',
            'app/common/uicontrols/**/**/*.js',
            'app/common/**/*.js',
            'app/common/**/*.html',
            'app/admin/**/*.js',
            'app/adt/**/*.js',
            'app/clinical/**/*.js',
            'app/document-upload/**/*.js',
            'app/home/**/*.js',
            'app/bedmanagement/**/*.js',
            'app/orders/**/*.js',
            'app/ot/**/*.js',
            'app/reports/**/*.js',
            'app/registration/**/*.js',
            'test/support/**/*.js',
            'test/unit/**/*.js',
            "test/unit/common/util/dateTimeFormatter.spec.js"
        ],
        exclude:[
            'app/components/moment/src/**/*.js',
            'app/components/moment/meteor/**/*.js',
            'app/components/jquery/src/**/*.js',
            'app/components/**/test/**/*.js'
        ],
        reporters: ['junit', (process.env.CI === 'true' ? 'dots' : 'progress'), 'coverage'],
        preprocessors: {
            'app/admin/**/*.js': ['coverage'],
            'app/adt/**/*.js': ['coverage'],
            'app/clinical/**/*.js': ['coverage'],
            'app/common/**/*.js': ['coverage'],
            'app/document-upload/**/*.js': ['coverage'],
            'app/home/**/*.js': ['coverage'],
            'app/orders/**/*.js': ['coverage'],
            'app/registration/**/*.js': ['coverage'],
            'app/reports/**/*.js': ['coverage'],
            'app/bedmanagement/**/*.js': ['coverage'],
            'app/ot/**/*.js': ['coverage'],
            'app/common/displaycontrols/**/views/*.html':['ng-html2js'],
            'app/common/concept-set/views/*.html':['ng-html2js'],
            'app/common/uicontrols/**/views/*.html': ['ng-html2js'],
            'app/clinical/**/**/*.html': ['ng-html2js']
        },
        coverageReporter: {
            reporters: [
                {type: 'json', dir: 'coverage/'},
                {type: 'html', dir: 'coverage/'},
                {type: 'text-summary'}
            ]
        },
        junitReporter: {
            outputFile: 'output/unit.xml',
            suite: 'unit'
        },
        ngHtml2JsPreprocessor: {
            stripPrefix: 'app',
            prependPrefix: '..',
            moduleName: 'ngHtml2JsPreprocessor'
        },
        proxies:{
            '/images/blank-user.gif' :'/base/app/images/blank-user.gif'
        }
    });
};
