name: bahmniapps Deploy
on:
  push:
      branches:
        - master
        - 'BAH-*'
  # workflow_run:
  #   workflows: ["Build Bahmni Apps"]
  #   types:
  #     - completed
env:
  BAHMNI_VERSION: 0.94
  BRANCH_NAME: BAH-1381
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.3]
        ruby: [2.5]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run:  npm install -g bower 
    - run:  npm install -g grunt-cli 
    - run:  gem install compass  
    - run: npm install --global yarn 
    - run : cd ui && npm cache clean --force && /bin/bash ./scripts/package.sh
    - uses: actions/upload-artifact@v2
      with:
        name: BahmniApps
        path: ui/target/bahmniapps.zip
  docker-build-publish:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build & Publish Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      # - uses: actions/checkout@v2
      
      - name: Checkout bahmni-package
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-package
          ref: ${{ env.BRANCH_NAME }}
          path: bahmni-package
      - uses: actions/download-artifact@v2
        with:
          name: BahmniApps
          path: bahmni-package/bahmni-web/resources
      - name: Download default_config.zip
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Bahmni/default-config/actions/artifacts | \
          jq -r '.artifacts[0].archive_download_url' | \
          xargs curl -L -o default_config.zip -H "Authorization: token ${{secrets.BAHMNI_PAT}}"
      # - run: cat default_config.zip
      - run: unzip -q -o default_config.zip
      - name: Build Docker Image
        run: |
          ls bahmni-package/bahmni-web/resources &&\
          ./bahmni-package/bahmni-docker/build_scripts/bahmni-web/docker_build.sh
      - name: List Docker Images
        run: docker images
      - name: Push Docker Images
        run: ./bahmni-package/bahmni-docker/build_scripts/bahmni-web/docker_publish.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}

